// app/[locale]/layout.js

import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { NextIntlClientProvider } from "next-intl"
import { getMessages } from "next-intl/server"
import { notFound } from "next/navigation"
import { twMerge } from "tailwind-merge"
import Header from "@/components/ui/header/Index"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function LocaleLayout({ children, params }) {
  params = await params
  const locale = params.locale

  let messages;
  try {
    messages = await getMessages({ locale });
  } catch (error) {
    console.log(error)
    notFound(); // Fallback to 404 if locale not found
  }

  return (
    <html lang={locale}>
      <body className={twMerge(geistSans.variable, geistMono.variable)}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header locale={locale} />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}